# Generated by Django 3.1 on 2020-09-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='opcoes',
        ),
    ]
