# Generated by Django 3.1 on 2020-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
    ]
