# Generated by Django 3.1 on 2020-08-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_despesa_situacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='situacao',
            new_name='status_pagamento',
        ),
    ]
