# Generated by Django 3.1 on 2020-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_despesa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
    ]
